# Generated by Django 5.0.6 on 2024-07-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_namenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namenumber',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='namenumber',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
